"""add is_verified to users

Revision ID: d7bd07854e8b
Revises: 2aef1baf8f0b
Create Date: 2026-05-18 08:36:17.283139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7bd07854e8b'
down_revision: Union[str, Sequence[str], None] = '2aef1baf8f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
